# Generated by Django 5.0.3 on 2024-03-19 23:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('media', models.FileField(upload_to='assets/', verbose_name='Media')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=100, verbose_name='Type')),
                ('duration', models.IntegerField(default=10, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start At')),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assets', models.ManyToManyField(related_name='playlist', to='core.asset', verbose_name='Assets')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('playlists', models.ManyToManyField(related_name='island', to='core.playlist', verbose_name='Playlists')),
            ],
            options={
                'verbose_name': 'Island',
                'verbose_name_plural': 'Islands',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Screen Name')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('layout', models.CharField(choices=[('FullScreen', 'Full Screen'), ('MainWith4Subs', 'Main With 4 Subs')], default='MainWith4Subs', max_length=100, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('islands', models.ManyToManyField(blank=True, related_name='screens', to='core.island', verbose_name='Islands')),
            ],
        ),
    ]
