# Generated by Django 5.0.3 on 2024-03-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'verbose_name': 'Screen', 'verbose_name_plural': 'Screens'},
        ),
        migrations.RemoveField(
            model_name='screen',
            name='islands',
        ),
        migrations.AddField(
            model_name='island',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='core.screen', verbose_name='Screen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='island',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='island', to='core.playlist', verbose_name='Playlists'),
        ),
    ]
