# Generated by Django 5.0.3 on 2024-03-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_screen_options_remove_screen_islands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='islands', to='core.playlist', verbose_name='Playlists'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='core.asset', verbose_name='Assets'),
        ),
    ]
