# Generated by Django 5.0.3 on 2024-03-24 00:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_island_playlists_alter_playlist_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='uuid',
            field=models.CharField(default=core.models.short_urlsafe_uuid, editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
