# Generated by Django 5.0.3 on 2024-03-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_screen_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='start_at',
        ),
        migrations.CreateModel(
            name='ScheduleBetweenDates',
            fields=[
                ('schedulebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.schedulebase')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
            bases=('core.schedulebase',),
        ),
        migrations.CreateModel(
            name='ScheduleOnOff',
            fields=[
                ('schedulebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.schedulebase')),
                ('val', models.BooleanField(verbose_name='Value')),
            ],
            bases=('core.schedulebase',),
        ),
        migrations.AddField(
            model_name='playlist',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='core.schedulebase', verbose_name='Schedule'),
            preserve_default=False,
        ),
    ]
