# Generated by Django 5.0.3 on 2024-03-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schedulebase_remove_playlist_end_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OnOff', 'OnOff'), ('BetweenDates', 'BetweenDates')], max_length=100, verbose_name='Type')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.RemoveField(
            model_name='scheduleonoff',
            name='schedulebase_ptr',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='core.schedule', verbose_name='Schedule'),
        ),
        migrations.DeleteModel(
            name='ScheduleBetweenDates',
        ),
        migrations.DeleteModel(
            name='ScheduleOnOff',
        ),
        migrations.DeleteModel(
            name='ScheduleBase',
        ),
    ]
