# Generated by Django 5.0.3 on 2024-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedule_remove_scheduleonoff_schedulebase_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Schedule'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
