# Generated by Django 4.2 on 2024-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_playlist_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
