# Generated by Django 4.2 on 2024-05-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_publisher_asset_created_at_asset_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=models.CharField(choices=[('FullScreen', 'Full Screen'), ('MainWith4Subs', 'Main With 4 Subs')], default='FullScreen', max_length=100, verbose_name='Layout'),
        ),
    ]
